export const USER_REQUEST_LOGIN = 'USER_REQUEST_LOGIN';

export const ACTION_FETCH_REQUEST = 'ACTION_FETCH_REQUEST';

export const USER_ADD_NEW_EXPENSE = 'USER_ADD_NEW_EXPENSE';

export const USER_DELETE_EXPENSE = 'USER_DELETE_EXPENSE';
